<center> <h1> Testing differents GAN architectures</h1>

<b>Autor:</b> Edwin Rueda <br>
<b>email:</b> ejrueda95g@gmail.com <br>
<b>github:</b> https://github.com/ejrueda <br>
<b>website:</b> http://edwinrueda.com/ <br>
<b> You can cite this work with</b>:

@software{edwin_rueda_2020_3843381,<br>
  author       = {Edwin Rueda},<br>
  title        = {ejrueda/MasterUFPA: zenodo release},<br>
  month        = may,<br>
  year         = 2020,<br>
  publisher    = {Zenodo},<br>
  version      = {zenodo},<br>
  doi          = {10.5281/zenodo.3843381},<br>
  url          = {https://doi.org/10.5281/zenodo.3843381}<br>
}

In [1]:
import numpy as np
import pandas as pd
from utilities import EdwinRueda_utils 

In [4]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LeakyReLU, Dropout

In [9]:
data = pd.read_csv("../data/all_counts_9_norm_rpkm_log2_preprocessed.csv", index_col=0)
data.head()

BB9      BB10      BB17      BB19       BB20      BB21      BB11  \
gene                                                                          
aaeA  5.542667  5.876225  5.189101  6.178741   6.258982  5.921482  6.565341   
aaeB  5.627977  5.436188  5.397088  5.493631   5.603751  5.716862  5.840627   
aaeR  5.645506  5.758852  5.107190  5.824890   5.487705  6.033795  5.710782   
aaeX  6.081770  6.043589  6.030808  6.358792  15.682419  6.129392  6.042647   
aas   6.224669  6.297153  6.297008  6.047021   6.038410  6.296795  6.295251   

          BB12       BB18  
gene                       
aaeA  6.308676   6.256590  
aaeB  6.132819   5.896502  
aaeR  6.302440  16.270368  
aaeX  6.134309  15.797839  
aas   6.598525   6.568365

In [79]:
reference_genes = open("../data/reference_genes.txt").read().splitlines()
print("Reference genes:", reference_genes)


['cysG', 'hcaT', 'idnT', 'rrsA', 'ihfB', 'ssrA', 'gyrA', 'recA', 'rpoB', 'rpoA', 'gyrB', 'rho', 'ftsZ', 'secA', 'rpoC', 'gmk', 'adk', 'rpoD', 'dnaG', 'glnA', 'recF']


#### Proposed GAN

In [62]:
noise_size = 100
#generator network
G = Sequential()
G.add(Dense(noise_size, input_shape=(noise_size,)))
G.add(Dense(data.shape[1], activation="tanh"))

In [68]:
noise_vector = tf.random.normal([3,100], stddev=.5, dtype=tf.float64)
print("Synthetic samples:")
synthetic_samples = G(noise_vector)
print(synthetic_samples)

Synthetic samples:
tf.Tensor(
[[ 0.34720555 -0.79775709 -0.52863513 -0.75752314  0.55298923 -0.54434526
   0.33151106  0.66808763 -0.71878254]
 [-0.45535186 -0.80779431 -0.83626951 -0.1454853   0.6785366   0.48325415
  -0.77847388  0.3542008  -0.25984561]
 [ 0.09374843  0.48956202  0.1856134  -0.17367753 -0.85278105  0.60133192
  -0.77491157 -0.22461589 -0.73580145]], shape=(3, 9), dtype=float64)


In [69]:
#discriminator network
D = Sequential()
D.add(Dense(data.shape[1], input_shape=(data.shape[1],)))
D.add(Dense(1, activation="sigmoid"))

In [70]:
print("predictions of the discriminator network:")
D(synthetic_samples)

predictions of the discriminator network:


<tf.Tensor: shape=(3, 1), dtype=float64, numpy=
array([[0.61147537],
       [0.61533635],
       [0.40878778]])>

#### principal component analysis for see the synthetic and real samples

In [71]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
